/**
 * Translation status data generated by Lunaria build
 */
export interface I18nStatus {
  /** ISO timestamp when this status was generated */
  generatedAt: string
  /** The source locale (English) */
  sourceLocale: {
    lang: string
    label: string
    totalKeys: number
  }
  /** Status for each target locale */
  locales: I18nLocaleStatus[]
}

export interface I18nLocaleStatus {
  /** Locale code (e.g., 'fr', 'zh-CN') */
  lang: string
  /** Display name (e.g., 'Français') */
  label: string
  /** Total number of translation keys */
  totalKeys: number
  /** Number of completed translations */
  completedKeys: number
  /** List of missing key paths (dot notation) */
  missingKeys: string[]
  /** Completion percentage (0-100) */
  percentComplete: number
  /** GitHub URL to edit this locale file */
  githubEditUrl: string
  /** GitHub URL to view history of this locale file */
  githubHistoryUrl: string
}
